### ISSUE TITLE
Logic App が Custom Vision のパーツで停止する

### ISSUE THREAD

**Issue by ytabuchi** [seosoft/AINightsBegineerTrack-JP#6]
実行はされるようになりました！ありがとうございます。issue #5 の続きですが、今度は Custom Vision からのアウトプットが取得できていない感じのエラーが出ています。以下は raw output です。

```json
{
    "statusCode": 404,
    "headers": {
        "apim-request-id": "c5813f8c-de65-4b0d-92e4-9225f5555cb5",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
        "x-content-type-options": "nosniff",
        "Timing-Allow-Origin": "*",
        "x-ms-apihub-cached-response": "false",
        "Date": "Fri, 29 Mar 2019 02:46:24 GMT",
        "Content-Length": "99",
        "Content-Type": "application/json"
    },
    "body": {
        "Code": "NotFoundProjectDefaultIteration",
        "Message": "Project has no default iteration"
    }
}
```

<img width="1238" alt="スクリーンショット 2019-03-29 11 48 31" src="https://user-images.githubusercontent.com/7854886/55206442-c8522f00-5219-11e9-81c1-6d5e0e96c5fe.png">

**Comment by seosoft** [comment]
Custom Visionでトレーニングされてないように見えます

＞"Code": "NotFoundProjectDefaultIteration",

**Comment by seosoft** [comment]
Custom Visionのバージョンが変わったことによる問題であることが判明。ワークショップコンテンツは3月末時点では、この部分はコケることが判明

**Comment by beachside-project** [comment]
I will check and fix doc.

**Comment by beachside-project** [comment]
Official で Henkさんが Http の Connector に変更するっぽいので、それをまって変更しましょうか。
Official 待たずにこっちで同じことを先に作った方が早いか。。。明日の夕方まで様子みて私で対応します。

**Comment by seosoft** [comment]
横浜さんの投稿をさっき見て「おぉぅ！」って思ってたところです。

**Comment by ytabuchi** [comment]
自分だけじゃなくてみんなできなかったのね。そもそも出来ないという状態からは回避されそうでよかったですー

**Comment by beachside-project** [comment]
updated. #14
